municipality_mapping = {
    '52001': 'Pasto',
    '52019': 'Albán',
    '52022': 'Aldana',
    '52036': 'Ancuya',
    '52051': 'Arboleda',
    '52079': 'Barbacoas',
    '52083': 'Belén',
    '52110': 'Buesaco',
    '52203': 'Colón',
    '52207': 'Consacá',
    '52210': 'Contadero',
    '52215': 'Córdoba',
    '52224': 'Cuaspud Carlosama',
    '52227': 'Cumbal',
    '52233': 'Cumbitara',
    '52240': 'Chachagüí',
    '52250': 'El Charco',
    '52254': 'El Peñol',
    '52256': 'El Rosario',
    '52258': 'El Tablón de Gómez',
    '52260': 'El Tambo',
    '52287': 'Funes',
    '52317': 'Guachucal',
    '52320': 'Guitarilla',
    '52323': 'Gualmatán',
    '52352': 'Iles',
    '52354': 'Imués',
    '52356': 'Ipiales',
    '52378': 'La Cruz',
    '52381': 'La Florida',
    '52385': 'La Llanada',
    '52390': 'La Tola',
    '52399': 'La Unión',
    '52405': 'Leiva',
    '52411': 'Linares',
    '52418': 'Los Andes',
    '52427': 'Magüí',
    '52435': 'Mallama',
    '52473': 'Mosquera',
    '52480': 'Nariño',
    '52490': 'Olaya Herrera',
    '52506': 'Ospina',
    '52520': 'Francisco Pizarro',
    '52540': 'Policarpa',
    '52560': 'Potosí',
    '52565': 'Providencia',
    '52573': 'Puerres',
    '52585': 'Pupiales',
    '52612': 'Ricaurte',
    '52621': 'Roberto Payán',
    '52678': 'Samaniego',
    '52683': 'Sandoná',
    '52685': 'San Bernardo',
    '52687': 'San Lorenzo',
    '52693': 'San Pablo',
    '52694': 'San Pedro de Cartago',
    '52696': 'Santa Bárbara',
    '52699': 'Santacruz',
    '52720': 'Sapuyes',
    '52786': 'Taminango',
    '52788': 'Tangua',
    '52835': 'San Andrés de Tumaco',
    '52838': 'Túquerres',
    '52885': 'Yacuanquer'
}

departaments_mapping = {
    "05": "Antioquia",
    "08": "Atlántico",
    "11": "Bogotá D.C.",
    "13": "Bolívar",
    "15": "Boyacá",
    "17": "Caldas",
    "18": "Caquetá",
    "19": "Cauca",
    "20": "Cesar",
    "23": "Córdoba",
    "25": "Cundinamarca",
    "27": "Chocó",
    "41": "Huila",
    "44": "La Guajira",
    "47": "Magdalena",
    "50": "Meta",
    "52": "Nariño",
    "54": "Norte de Santander",
    "63": "Quindío",
    "66": "Risaralda",
    "68": "Santander",
    "70": "Sucre",
    "73": "Tolima",
    "76": "Valle del Cauca",
    "81": "Arauca",
    "85": "Casanare",
    "86": "Putumayo",
    "88": "Archipiélago de San Andrés, Providencia y Santa Catalina",
    "91": "Amazonas",
    "94": "Guainía",
    "95": "Guaviare",
    "97": "Vaupés",
    "99": "Vichada"
}

estratum_mapping = {
    1: 'Bajo bajo',
    2: 'Bajo',
    3: 'Medio-bajo',
    4: 'Medio',
    5: 'Medio-alto',
    6: 'Alto'
}

yn_mapping = {
    1: 'Si',
    2: 'No'
}

family_type_mapping = {
    1: 'Nuclear biparental',
    2: 'Nuclear monoparental',
    3: 'Extenso biparental',
    4: 'Extenso monoparental',
    5: 'Compuesto biparental',
    6: 'Compuesto monoparental',
    7: 'Uniparental'
}

role_mapping = {
    1: 'Jefe(a) de Familia',
    2: 'Conyuge o Compañero(a)',
    3: 'Hijo(a)',
    4: 'Hermano(a)',
    5: 'Padre o Madre',
    6: 'Otros',

}

sex_mapping = {
    1: 'Hombre',
    2: 'Mujer',
    3: 'Indeterminado',
}
type_id_mapping_reverse = {
    1: 'CC',
    2: 'CD',
    3: 'CE',
    4: 'MS',
    5: 'CN',
    6: 'PA',
    7: 'PE',
    8: 'PT',
    9: 'RC',
    10: 'TI',
}
type_id_mapping = {
    'CC': 1,
    'CD': 2,
    'CE': 3,
    'MS': 4,
    'CN': 5,
    'PA': 6,
    'PE': 7,
    'PT': 8,
    'RC': 9,
    'TI': 10,
}

eps_member = {
    "CCF033": "CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE",
    "CCF050": "CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO 'COMFAORIENTE'",
    "CCF055": "CAJA DE DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO",
    "CCF102": "CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ COMFACHOCO",
    "CCFC20": "CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ COMFACHOCO-CM",
    "CCFC33": "CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE-CM",
    "CCFC50": "CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO - COMFAORIENTE -CM",
    "CCFC55": "CAJA DE DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO-CM",
    "EAS016": "EMPRESAS PUBLICAS DE MEDELLIN-DEPARTAMENTO MEDICO",
    "EAS027": "FONDO DE PASIVO SOCIAL DE LOS FERROCARRILES NALES",
    "EPS001": "ALIANSALUD ENTIDAD PROMOTORA DE SALUD S.A.",
    "EPS002": "SALUD  TOTAL  S.A.  E.P.S.",
    "EPS005": "E.P.S.  SANITAS  S.A.",
    "EPS008": "COMPENSAR   E.P.S.",
    "EPS010": "EPS Y MEDICINA PREPAGADA SURAMERICANA S.A",
    "EPS012": "COMFENALCO  VALLE  E.P.S.",
    "EPS017": "E.P.S.  FAMISANAR  LTDA.",
    "EPS018": "EPS SERVICIO OCCIDENTAL DE SALUD  S.A. - EPS S.O.S. S.A.",
    "EPS025": "CAPRESOCA  EPS",
    "EPS037": "LA NUEVA EPS S.A.",
    "EPS040": "SAVIA SALUD EPS -CM",
    "EPS041": "LA NUEVA EPS S.A.-CM",
    "EPS042": "COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD",
    "EPS046": "FUNDACIÓN SALUD MIA EPS",
    "EPS047": "SALUD BOLIVAR EPS SAS",
    "EPS048": "ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD EPS-S MUTUAL SER EPS-S",
    "EPSC25": "CAPRESOCA  EPS-CM",
    "EPSC34": "CAPITAL SALUD-CM",
    "EPSI01": "ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA  DUSAKAWI",
    "EPSI03": "ASOCIACIÓN INDÍGENA DEL CAUCA",
    "EPSI04": "ANASWAYUU",
    "EPSI05": "MALLAMAS",
    "EPSI06": "PIJAOS SALUD EPSI",
    "EPSIC1": "ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA DUSAKAWI-CM",
    "EPSIC3": "ASOCIACIÓN INDÍGENA DEL CAUCA - AIC -CM",
    "EPSIC4": "ANASWAYUU-CM",
    "EPSIC5": "MALLAMAS-CM",
    "EPSIC6": "PIJAOS SALUD EPSI-CM",
    "EPSS01": "ALIANSALUD ENTIDAD PROMOTORA DE SALUD S.A.-CM",
    "EPSS02": "SALUD  TOTAL  S.A.  E.P.S. CM",
    "EPSS05": "E.P.S.  SANITAS  S.A.-CM",
    "EPSS08": "COMPENSAR   E.P.S.-CM",
    "EPSS10": "EPS Y MEDICINA PREPAGADA SURAMERICANA S.A-CM",
    "EPSS12": "COMFENALCO  VALLE  E.P.S.-CM",
    "EPSS17": "E.P.S.  FAMISANAR  LTDA.-CM",
    "EPSS18": "EPS SERVICIO OCCIDENTAL DE SALUD  S.A. - EPS S.O.S. S.A.-CM",
    "EPSS34": "CAPITAL SALUD",
    "EPSS37": "NUEVA EPS S.A. -CM",
    "EPSS40": "SAVIA SALUD EPS",
    "EPSS41": "LA NUEVA EPS S.A.",
    "EPSS42": "COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD -CM",
    "EPSS46": "FUNDACIÓN SALUD MIA - CM",
    "EPSS47": "SALUD BOLIVA EPS SAS CM",
    "EPSS48": "ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD EPS-S MUTUAL SER EPS-S - CM",
    "ESS024": "COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA LTDA. COOSALUD E.S.S.",
    "ESS062": "ASOCIACIÓN MUTUAL LA ESPERANZA ASMET  SALUD",
    "ESS118": "ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO E.S.S. EMSSANAR E.S.S.",
    "ESS207": "ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD ESS",
    "ESSC07": "ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD ESS-CM",
    "ESSC18": "ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO E.S.S. EMSSANAR E.S.S.-CM",
    "ESSC24": "COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA LTDA. COOSALUD E.S.S.-CM",
    "ESSC62": "ASOCIACIÓN MUTUAL LA ESPERANZA ASMET  SALUD-CM",
    "INP001": "INPEC",
    "RES002": "ECOPETROL",
    "RES004": "MAGISTERIO",
    "RES005": "UATLANTICO",
    "RES006": "CAPRUIS",
    "RES007": "UVALLE",
    "RES008": "UNISALUD",
    "RES009": "UCAUCA",
    "RES010": "UCARTAGENA",
    "RES012": "UCORDOBA",
    "RES013": "UNARIÑO",
    "RES014": "UPTC"
}


dict_options_ese = {
    "5200100107": "cehani ese",
    "5200100441": "universidad de nariño",
    "5200100739": "unidad administrativa especial de aeronáutica civil - aerocivil",
    "5200101102": "e.s.e. hospital universitario departamental de nariño",
    "5200101457": "empresa social del estado pasto salud e.s.e.",
    "5201901434": "ese centro de salud san jose",
    "5202201506": "e.s.e. centro de salud nuestra señora del pilar",
    "5203600988": "centro de salud ancuya e.s.e.",
    "5205101413": "e.s.e centro de salud san miguel",
    "5207900055": "asociacion de autoridades y cabildos awa unipa",
    "5207901407": "e.s.e. hospital san antonio de barbacoas",
    "5208301384": "e.s.e. centro de salud belen",
    "5211001504": "e.s.e. centro de salud virgen de lourdes",
    "5220301389": "e.s.e. centro de salud la buena esperanza",
    "5220700926": "centro de salud de consaca empresa social del estado",
    "5221001762": "centro de salud sagrado corazon de jesus e.s.e.",
    "5221500494": "centro de salud indigena del resguardo de males",
    "5221500902": "centro de salud de san bartolome de cordoba ese",
    "5222400108": "ips indigena de carlosama de la asociacion de autoridades indigenas de los pastos",
    "5222400914": "centro de salud cuaspud-carlosama empresa social del estado",
    "5222700091": "ips intercultural indigena de los cabildos del gran cumbal panan y mayasquer",
    "5222700110": "ips del cabildo indigena de chiles",
    "5222700321": "ese hospital cumbal",
    "5223301542": "e.s.e. san pedro de cumbitara",
    "5224001399": "e.s.e. centro de salud nuestra señora de fátima",
    "5225000974": "hospital sagrado corazón de jesús empresa social del estado de el charco",
    "5225401388": "e.s.e centro de salud san isidro de el peñol",
    "5225601409": "ese de primer nivel de el municipio de el rosario",
    "5225801507": "e.s.e. centro de salud del tablon de gomez",
    "5225801827": "ips-i del pueblo inga en aponte",
    "5226001436": "centro hospital san luis e.s.e.",
    "5228701440": "centro de salud funes e.s.e.",
    "5231700077": "ips-i asociacion de cabildos de guachucal y colimba",
    "5231700660": "hospital guachucal ese",
    "5231701009": "ips indigena del resguardo de muellamues",
    "5232000371": "centro hospital guaitarilla e.s.e.",
    "5232301390": "centro de salud señor de los milagros de gualmatán - empresa social del estado - e.s.e.",
    "5235200407": "centro de salud iles e.s.e.",
    "5235401414": "empresa social del estado santiago apostol e.s.e.",
    "5235600097": "asociacion de cabildos indigenas zona ipiales",
    "5235600356": "hospital civil de ipiales ese",
    "5235601166": "institucion prestadora de servicios de salud indígena guaitara",
    "5235601503": "ips municipal de ipiales e.s.e.",
    "5235601734": "ips indígena mallamás",
    "5237800240": "hospital el buen samaritano e.s.e. la cruz",
    "5238101502": "centro hospital de la florida empresa social del estado",
    "5238501829": "ese centro de salud san juan bosco",
    "5239001462": "empresa social del estado centro de salud nuestra señora del carmen",
    "5239900234": "e.s.e hospital eduardo santos",
    "5239900886": "centro de salud municipal nivel i luis acosta e.s.e",
    "5240501543": "ese centro de salud san jose de leiva",
    "5241100896": "e.s.e. juan pablo ii del municipio de linares",
    "5241801463": "e.s.e centro de salud de los andes",
    "5242700696": "centro de salud saul quiñones e.s.e.",
    "5243500903": "centro de salud santiago de mallama e.s.e.",
    "5247301525": "e.s.e. centro de salud san francisco",
    "5248001387": "e.s.e. centro de salud san sebastian",
    "5249001485": "centro de salud camilo hurtdao cifuentes ese.",
    "5250601433": "centro de salud san miguel arcangel de ospina ese",
    "5252001392": "e.s.e. centro de salud señor del mar",
    "5254001487": "e.s.e. centro de salud policarpa",
    "5256000237": "e.s.e centro hospital luis antonio montero",
    "5256500972": "centro de salud de providencia e.s.e.",
    "5257300562": "centro hospital nuestro señor de la divina misericordia puerres e.s.e.",
    "5258500933": "centro de salud san juan bautista de pupiales empresa social del estado",
    "5261201394": "hospital ricaurte empresa social del estado",
    "5262101493": "e.s.e. centro hospital las mercedes",
    "5267800613": "ese hospital lorencita villegas de santos",
    "5268300609": "ese hospital clarita santos de sandona",
    "5268501378": "ese centro de salud san bernardo",
    "5268701557": "e.s.e. centro de salud san lorenzo",
    "5269300351": "hospital san carlos e.s.e.",
    "5269401373": "e.s.e. centro de salud municipal de cartago",
    "5269601494": "e.s.e. centro de salud santa barbara iscuande",
    "5269900716": "ips indigena mingasalud resguardo indigena de guachavez",
    "5269901368": "e.s.e. centro de salud guachavés",
    "5272001059": "centro de salud sapuyes e.s.e.",
    "5278601536": "e.s.e. centro hospital san juan bautista",
    "5278801372": "centro de salud hermes andrade mejia ese tangua",
    "5283500260": "hospital san andres e.s.e.",
    "5283500905": "centro hospital divino niño empresa social del estado",
    "5283800483": "ips indigena julian carlosama",
    "5288501383": "centro de saludya e.s.e. de yacuanquer"
}


canalizacion = {
  1: "Vacunación",
  2: "Atención en salud de promoción y mantenimiento por médico",
  3: "Atención en salud por medicina general",
  4: "Atención en salud en un servicio de Urgencias",
  5: "Profilaxis y remoción de placa bacteriana y/o detartraje supragingival",
  6: "Activación de ruta por sospecha de violencias",
  7: "Prueba rápida treponémica",
  8: "Prueba rápida para VIH",
  9: "Asesoría pre y post test VIH",
  10: "Prueba rápida de hepatitis B",
  11: "Prueba rápida de hepatitis C",
  12: "Prueba de embarazo",
  13: "Asesoría en anticoncepción por médico o enfermera",
  14: "Tamizaje de riesgo cardiovascular",
  15: "Tamizaje de cáncer de cuello uterino (citología)",
  16: "Suministro de anticonceptivos",
  17: "Suministro de preservativos",
  18: "Asesoría en anticoncepción",
  19: "Tamizaje para cáncer de mama",
  20: "Tamizaje para cáncer de próstata (PSA)",
  21: "Tamizaje para cáncer de colon"
}


jobs = {
    "110": "Oficiales de las Fuerzas Militares",
    "210": "Suboficiales de las Fuerzas Militares",
    "310": "Otros miembros de las Fuerzas Militares",
    "1111": "Directores formuladores de políticas y normas",
    "1112": "Directores del gobierno",
    "1113": "Jefes de comunidades étnicas",
    "1114": "Dirigentes de organizaciones con un interés específico partidos políticos, sindicatos y organizaciones sociales",
    "1120": "Directores y gerentes generales",
    "1211": "Directores financieros",
    "1212": "Directores de recursos humanos",
    "1213": "Directores de políticas y planificación",
    "1219": "Directores de administración y servicios no clasificados en otros grupos primarios",
    "1221": "Directores de ventas y comercialización",
    "1222": "Directores de publicidad y relaciones públicas",
    "1223": "Directores de investigación y desarrollo",
    "1311": "Directores de producción agropecuaria y silvicultura",
    "1312": "Directores de producción de piscicultura y pesca",
    "1321": "Directores de industrias manufactureras",
    "1322": "Directores de explotaciones de minería",
    "1323": "Directores de empresas de construcción",
    "1324": "Directores de empresas de abastecimiento, distribución y afines",
    "1330": "Directores de servicios de tecnología de la información y las comunicaciones",
    "1341": "Directores de servicios de cuidados infantiles",
    "1342": "Directores de servicios de salud",
    "1343": "Directores de servicios de atención a personas mayores",
    "1344": "Directores de servicios de bienestar social",
    "1345": "Directores de servicios de educación",
    "1346": "Gerentes de sucursales de bancos, de servicios financieros y de seguros",
    "1349": "Directores y gerentes de servicios profesionales no clasificados en otros grupos primarios",
    "1411": "Gerentes de hoteles",
    "1412": "Gerentes de restaurantes",
    "1420": "Gerentes de comercios al por mayor y al por menor",
    "1431": "Gerentes de centros deportivos, de esparcimiento y culturales",
    "1439": "Otros gerentes de servicios no clasificados en otros grupos primarios",
    "2111": "Físicos y astrónomos",
    "2112": "Meteorólogos",
    "2113": "Químicos",
    "2114": "Geólogos y geofísicos",
    "2120": "Matemáticos, actuarios y estadísticos",
    "2131": "Biólogos, botánicos, zoólogos y afines",
    "2132": "Agrónomos, silvicultores, zootecnistas y afines",
    "2133": "Profesionales de la protección medioambiental",
    "2141": "Ingenieros industriales y de producción",
    "2142": "Ingenieros civiles",
    "2143": "Ingenieros medioambientales",
    "2144": "Ingenieros mecánicos",
    "2145": "Ingenieros químicos",
    "2146": "Ingenieros de minas, metalúrgicos y afines",
    "2149": "Ingenieros no clasificados en otros grupos primarios",
    "2151": "Ingenieros electricistas",
    "2152": "Ingenieros electrónicos",
    "2153": "Ingenieros de telecomunicaciones",
    "2161": "Arquitectos constructores",
    "2162": "Arquitectos paisajistas",
    "2163": "Diseñadores de productos y de prendas",
    "2164": "Planificadores urbanos, regionales y de tránsito",
    "2165": "Cartógrafos y topógrafos",
    "2166": "Diseñadores gráficos y multimedia",
    "2211": "Médicos generales",
    "2212": "Médicos especialistas",
    "2221": "Profesionales de enfermería",
    "2222": "Profesionales de partería",
    "2230": "Profesionales de medicina tradicional y alternativa",
    "2240": "Paramédicos e instrumentadores quirúrgicos",
    "2250": "Veterinarios",
    "2261": "Odontólogos",
    "2262": "Farmacéuticos",
    "2263": "Profesionales de la salud y la higiene laboral y ambiental",
    "2264": "Fisioterapeutas",
    "2265": "Dietistas y nutricionistas",
    "2266": "Fonoaudiólogos y terapeutas del lenguaje",
    "2267": "Optómetras",
    "2269": "Otros profesionales de la salud no clasificados en otros grupos primarios",
    "2310": "Profesores de instituciones de educación superior",
    "2320": "Profesores de formación profesional",
    "2330": "Profesores de educación secundaria",
    "2341": "Profesores de educación primaria",
    "2342": "Profesores de primera infancia",
    "2351": "Especialistas en métodos pedagógicos",
    "2352": "Profesores de educación especial e inclusiva",
    "2353": "Otros profesores de idiomas",
    "2354": "Otros profesores de música",
    "2355": "Otros profesores de artes",
    "2356": "Instructores de tecnología de la información",
    "2359": "Otros profesionales de la educación no clasificados en otros grupos primarios",
    "2411": "Contadores",
    "2412": "Asesores financieros y de inversiones",
    "2413": "Analistas financieros",
    "2421": "Analistas de gestión y organización",
    "2422": "Profesionales en políticas de administración",
    "2423": "Profesionales de gestión de talento humano",
    "2424": "Profesionales en formación y desarrollo de personal",
    "2431": "Profesionales de la publicidad y la comercialización",
    "2432": "Profesionales de relaciones públicas",
    "2433": "Profesionales de ventas técnicas y médicas (excluyendo las TIC)",
    "2434": "Profesionales de ventas de tecnología de la información y las comunicaciones",
    "2511": "Analistas de sistemas",
    "2512": "Desarrolladores de software",
    "2513": "Desarrolladores web y multimedia",
    "2514": "Programadores de aplicaciones",
    "2519": "Desarrolladores y analistas de software y multimedia no clasificados en otros grupos primarios",
    "2521": "Diseñadores y administradores de bases de datos",
    "2522": "Administradores de sistemas",
    "2523": "Profesionales en redes de computadores",
    "2529": "Profesionales en bases de datos y en redes de computadores no clasificados en otros grupos primarios",
    "2611": "Abogados",
    "2612": "Jueces",
    "2619": "Profesionales en derecho no clasificados en otros grupos primarios",
    "2621": "Archivistas y curadores de arte",
    "2622": "Bibliotecarios, documentalistas y afines",
    "2631": "Economistas",
    "2632": "Sociólogos, antropólogos y afines",
    "2633": "Filósofos, historiadores y especialistas en ciencias políticas",
    "2634": "Psicólogos",
    "2635": "Profesionales del trabajo social y consejeros",
    "2636": "Profesionales religiosos",
    "2641": "Autores y otros escritores",
    "2642": "Periodistas",
    "2643": "Traductores, intérpretes y otros lingüistas",
    "2651": "Escultores, pintores artísticos y afines",
    "2652": "Compositores, músicos y cantantes",
    "2653": "Coreógrafos y bailarines",
    "2654": "Directores y productores de cine, de teatro y afines",
    "2655": "Actores",
    "2656": "Locutores de radio, televisión y otros medios de comunicación",
    "2659": "Artistas creativos e interpretativos no clasificados en otros grupos primarios",
    "3111": "Técnicos en ciencias físicas y químicas",
    "3112": "Técnicos en ingeniería civil",
    "3113": "Electrotécnicos",
    "3114": "Técnicos en electrónica",
    "3115": "Técnicos en ingeniería mecánica",
    "3116": "Técnicos en química industrial",
    "3117": "Técnicos de minas y metalurgia",
    "3118": "Delineantes y dibujantes técnicos",
    "3119": "Técnicos en ciencias físicas y en ingeniería no clasificados en otros grupos primarios",
    "3121": "Supervisores de minas",
    "3122": "Supervisores de industrias manufactureras",
    "3123": "Supervisores de la construcción",
    "3131": "Operadores de plantas de producción de energía",
    "3132": "Operadores de incineradores, instalaciones de tratamiento de agua y afines",
    "3133": "Controladores de instalaciones de procesamiento de productos químicos",
    "3134": "Operadores de instalaciones de refinación de petróleo y gas natural",
    "3135": "Operadores de procesos de producción de metales",
    "3139": "Técnicos en control de procesos no clasificados en otros grupos primarios",
    "3141": "Técnicos en ciencias biológicas (excluyendo la medicina)",
    "3142": "Técnicos agropecuarios",
    "3143": "Técnicos forestales",
    "3151": "Oficiales maquinistas en navegación",
    "3152": "Capitanes, oficiales de cubierta y prácticos",
    "3153": "Pilotos de aviación y afines",
    "3154": "Controladores de tráfico aéreo y marítimo",
    "3155": "Técnicos en seguridad aeronáutica",
    "3211": "Técnicos en aparatos de diagnóstico y tratamiento médico",
    "3212": "Técnicos de laboratorios médicos",
    "3213": "Técnicos y asistentes farmacéuticos",
    "3214": "Técnicos de prótesis médicas y dentales",
    "3221": "Técnicos y profesionales del nivel medio en enfermería",
    "3222": "Técnicos y profesionales del nivel medio en partería",
    "3230": "Técnicos y profesionales del nivel medio en medicina tradicional y alternativa",
    "3240": "Técnicos y asistentes veterinarios",
    "3251": "Higienistas y asistentes odontológicos",
    "3252": "Técnicos en documentación sanitaria",
    "3253": "Trabajadores comunitarios de la salud",
    "3254": "Técnicos en optometría y ópticas",
    "3255": "Técnicos y asistentes terapeutas",
    "3256": "Asistentes médicos",
    "3257": "Inspectores de seguridad, salud ocupacional, medioambiental y afines",
    "3258": "Técnicos en atención prehospitalaria",
    "3259": "Otros técnicos y profesionales del nivel medio de la salud, no clasificados en otros grupos primarios",
    "3311": "Agentes de bolsa, cambio y otros servicios financieros",
  "3315": "Tasadores y evaluadores",
    "3321": "Agentes de seguros",
    "3322": "Representantes comerciales",
    "3323": "Agentes de compras",
    "3324": "Agentes de operaciones comerciales y consignatarios",
    "3331": "Declarantes o gestores de aduana",
    "3332": "Organizadores de conferencias y eventos",
    "3333": "Agentes de empleo y contratistas de mano de obra",
    "3334": "Agentes inmobiliarios",
    "3339": "Agentes de servicios comerciales no clasificados en otros grupos primarios",
    "3341": "Supervisores de oficina",
    "3342": "Secretarios jurídicos",
    "3343": "Secretarios administrativos y ejecutivos",
    "3344": "Secretarios médicos",
    "3351": "Agentes de aduana e inspectores de frontera",
    "3352": "Agentes de administración tributaria",
    "3353": "Agentes de servicios de seguridad social",
    "3354": "Agentes gubernamentales de expedición de licencias",
    "3355": "Inspectores de policía y detectives",
    "3359": "Agentes de gobierno y profesionales del nivel medio para la aplicación de regulaciones no clasificados en otros grupos primarios",
    "3411": "Técnicos y profesionales del nivel medio del derecho de servicios legales y afines",
    "3412": "Trabajadores y asistentes sociales",
    "3413": "Auxiliares laicos de las religiones",
    "3421": "Atletas y deportistas",
    "3422": "Entrenadores, instructores y árbitros de actividades deportivas",
    "3423": "Instructores de educación física y actividades recreativas",
    "3431": "Fotógrafos",
    "3432": "Diseñadores y decoradores de interiores",
    "3433": "Técnicos en galerías de arte, museos y bibliotecas",
    "3434": "Chefs",
    "3435": "Otros técnicos y profesionales del nivel medio en actividades culturales y artísticas",
    "3511": "Técnicos en operaciones de tecnología de la información y las comunicaciones",
    "3512": "Técnicos en asistencia y soporte al usuario de tecnología de la información y las comunicaciones",
    "3513": "Técnicos en redes y sistemas de computación",
    "3514": "Técnicos de la Web",
    "3521": "Técnicos de radiodifusión y grabación audiovisual",
    "3522": "Técnicos de ingeniería de las telecomunicaciones",
    "4110": "Oficinistas generales",
    "4120": "Secretarios generales",
    "4131": "Operadores de máquinas de procesamiento de texto y mecanógrafos",
    "4132": "Grabadores de datos",
    "4211": "Cajeros de bancos y afines",
    "4212": "Receptores de apuestas y afines",
    "4213": "Prestamistas",
    "4214": "Cobradores y afines",
    "4221": "Empleados y consultores de viajes",
    "4222": "Empleados de centros de llamadas",
    "4223": "Telefonistas",
    "4224": "Recepcionistas de hoteles",
    "4225": "Empleados de ventanillas de informaciones",
    "4226": "Recepcionistas generales",
    "4227": "Entrevistadores de encuestas y de investigaciones de mercados",
    "4229": "Otros empleados de servicios de información al cliente no clasificados en otros grupos primarios",
    "4311": "Auxiliares de contabilidad y cálculo de costos",
    "4312": "Auxiliares de servicios estadísticos, financieros y de seguros",
    "4313": "Auxiliares encargados de las nóminas",
    "4321": "Empleados de control de abastecimientos e inventario",
    "4322": "Empleados de servicios de apoyo a la producción",
    "4323": "Empleados de servicios de transporte",
    "4411": "Empleados de bibliotecas",
    "4412": "Empleados de servicios de correos",
    "4413": "Codificadores de datos, correctores de pruebas de imprenta y afines",
    "4414": "Escribientes públicos y afines",
    "4415": "Empleados de archivos",
    "4416": "Empleados del servicio de personal",
    "4419": "Otro personal de apoyo administrativo no clasificados en otros grupos primarios",
    "5111": "Personal de servicio a pasajeros",
    "5112": "Revisores y cobradores de los transportes públicos",
    "5113": "Guías",
    "5120": "Cocineros",
    "5131": "Meseros",
    "5132": "Bármanes",
    "5141": "Peluqueros",
    "5142": "Especialistas en tratamientos de belleza y afines",
    "5151": "Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos",
    "5152": "Mayordomos domésticos",
    "5153": "Conserjes y afines",
    "5161": "Astrólogos, adivinos y trabajadores afines",
    "5162": "Acompañantes",
    "5163": "Personal de servicios funerarios y embalsamadores",
    "5164": "Cuidadores de animales",
    "5165": "Instructores de conducción",
    "5169": "Otros trabajadores de servicios personales no clasificados en otros grupos primarios",
    "5211": "Vendedores de quioscos y de puestos de mercado",
    "5212": "Vendedores ambulantes de alimentos preparados para consumo inmediato",
    "5221": "Comerciantes de tiendas",
    "5222": "Supervisores de tiendas y almacenes",
    "5223": "Vendedores y auxiliares de venta en tiendas, almacenes y afines",
    "5230": "Cajeros de comercio, taquilleros y expendedores de boletas",
    "5241": "Modelos de moda, arte y publicidad",
    "5242": "Demostradores de tiendas, almacenes y afines",
    "5243": "Vendedores puerta a puerta",
    "5244": "Vendedores a través de medios tecnológicos",
    "5245": "Expendedores de combustibles para vehículos",
    "5246": "Vendedores de comidas al mostrador",
    "5249": "Otros vendedores no clasificados en otros grupos primarios",
    "5311": "Cuidadores de niños",
    "5312": "Auxiliares de maestros",
    "5321": "Trabajadores de los cuidados personales en instituciones",
    "5322": "Trabajadores de los cuidados personales a domicilio",
    "5329": "Trabajadores de los cuidados personales en servicios de salud no clasificados en otros grupos primarios",
    "5411": "Bomberos y rescatistas",
    "5412": "Policías",
    "5413": "Guardianes de prisión",
    "5414": "Guardias de seguridad",
    "5419": "Personal de los servicios de protección no clasificados en otros grupos primarios",
  "6111": "Agricultores y trabajadores calificados de cultivos extensivos",
    "6112": "Agricultores y trabajadores calificados de plantaciones de árboles y arbustos",
    "6113": "Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines",
    "6114": "Agricultores y trabajadores calificados de cultivos mixtos",
    "6121": "Criadores de ganado y trabajadores de la cría de animales domésticos (excepto aves de corral)",
    "6122": "Avicultores y trabajadores calificados de la avicultura",
    "6123": "Criadores y trabajadores calificados de la apicultura y la sericicultura",
    "6129": "Criadores y trabajadores pecuarios calificados, avicultores y criadores de insectos no clasificados en otros grupos primarios",
    "6130": "Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado",
    "6210": "Trabajadores forestales calificados y afines",
    "6221": "Trabajadores de explotaciones de acuicultura",
    "6222": "Pescadores de agua dulce y en aguas costeras",
    "6223": "Pescadores de alta mar",
    "6224": "Cazadores y tramperos",
    "6310": "Trabajadores agrícolas de subsistencia",
    "6320": "Trabajadores pecuarios de subsistencia",
    "6330": "Trabajadores agropecuarios de subsistencia",
    "6340": "Pescadores, cazadores, tramperos y recolectores de subsistencia",
    "7111": "Constructores de casas",
    "7112": "Albañiles",
    "7113": "Labrantes, tronzadores y grabadores de piedra",
    "7114": "Operarios en cemento armado, enfoscadores y afines",
    "7115": "Carpinteros de armar y de obra blanca",
    "7119": "Oficiales y operarios de la construcción de obra gruesa y afines no clasificados en otros grupos primarios",
    "7121": "Techadores",
    "7122": "Enchapadores, parqueteros y colocadores de suelos",
    "7123": "Revocadores",
    "7124": "Instaladores de material aislante y de insonorización",
    "7125": "Cristaleros",
    "7126": "Fontaneros e instaladores de tuberías",
    "7127": "Mecánicos montadores de aire acondicionado y refrigeración",
    "7131": "Pintores y empapeladores",
    "7132": "Barnizadores y afines",
    "7133": "Limpiadores de fachadas y deshollinadores",
    "7211": "Moldeadores y macheros",
    "7212": "Soldadores y oxicortadores",
    "7213": "Chapistas y caldereros",
    "7214": "Montadores de estructuras metálicas",
    "7215": "Aparejadores y empalmadores de cables",
    "7221": "Herreros y forjadores",
    "7222": "Herramentistas y afines",
    "7223": "Ajustadores y operadores de máquinas herramientas",
    "7224": "Pulidores de metales y afiladores de herramientas",
    "7231": "Mecánicos y reparadores de vehículos de motor",
    "7232": "Mecánicos y reparadores de sistemas y motores de aeronaves",
    "7233": "Mecánicos y reparadores de máquinas agrícolas e industriales",
    "7234": "Reparadores de bicicletas y afines",
    "7311": "Mecánicos y reparadores de instrumentos de precisión",
    "7312": "Fabricantes y afinadores de instrumentos musicales",
    "7314": "Alfareros y ceramistas (barro y arcilla)",
    "7315": "Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio",
    "7316": "Rotulistas, pintores decorativos y grabadores",
    "7321": "Preimpresores y afines",
    "7322": "Impresores",
    "7323": "Encuadernadores y afines",
    "7331": "Tejedores con telares",
    "7332": "Tejedores con agujas",
    "7333": "Otros tejedores",
    "7341": "Cesteros y mimbreros",
    "7342": "Sombrereros artesanales",
    "7351": "Talladores piezas artesanales de madera",
    "7352": "Decoradores de piezas artesanales en madera",
    "7361": "Joyeros",
    "7362": "Orfebres y plateros",
    "7363": "Bisuteros",
    "7370": "Artesanos del cuero",
    "7391": "Artesanos de papel",
    "7392": "Artesanos del hierro y otros metales",
    "7393": "Artesanos de las semillas y cortezas vegetales",
    "7399": "Artesanos de otros materiales no clasificados en otros grupos primarios",
    "7411": "Electricistas de obras y afines",
    "7412": "Mecánicos y ajustadores electricistas",
    "7413": "Instaladores y reparadores de líneas eléctricas",
    "7421": "Mecánicos y reparadores en electrónica",
    "7422": "Instaladores y reparadores en tecnología de la información y las comunicaciones",
"7511": "Carniceros, pescaderos y afines",
    "7512": "Panaderos, pasteleros y confiteros",
    "7513": "Operarios de la elaboración de productos lácteos",
    "7514": "Operarios de la conservación de frutas, legumbres, verduras y afines",
    "7515": "Catadores y clasificadores de alimentos y bebidas",
    "7516": "Preparadores y elaboradores de tabaco y sus productos",
    "7521": "Operarios del tratamiento de la madera",
    "7522": "Ebanistas y carpinteros (excluye carpinteros de armar y de obra blanca)",
    "7523": "Ajustadores y operadores de máquinas para trabajar madera",
    "7531": "Sastres, modistos, peleteros y sombrereros",
    "7532": "Patronistas y cortadores de tela, cuero y afines",
    "7533": "Costureros, bordadores y afines",
    "7534": "Tapiceros, colchoneros y afines",
    "7535": "Apelambradores, pellejeros y curtidores",
    "7536": "Zapateros y afines",
    "7541": "Buzos",
    "7542": "Dinamiteros y pegadores",
    "7543": "Clasificadores y probadores de productos (excluyendo alimentos y bebidas)",
    "7544": "Fumigadores y otros controladores de plagas y malas hierbas",
    "7549": "Otros oficiales, operarios y oficios relacionados no clasificados en otros grupos primarios",
    "8111": "Mineros y operadores de instalaciones mineras",
    "8112": "Operadores de instalaciones de procesamiento de minerales y rocas",
    "8113": "Perforadores y sondistas de pozos y afines",
    "8114": "Operadores de máquinas para fabricar cemento y otros productos minerales",
    "8121": "Operadores de instalaciones de procesamiento de metales",
    "8122": "Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales",
    "8131": "Operadores de plantas y máquinas de productos químicos",
    "8132": "Operadores de máquinas para fabricar productos fotográficos",
    "8141": "Operadores de máquinas para fabricar productos de caucho",
    "8142": "Operadores de máquinas para fabricar productos de material plástico",
    "8143": "Operadores de máquinas para fabricar productos de papel",
    "8151": "Operadores de máquinas de preparación de fibras, hilado y devanado",
    "8152": "Operadores de telares y otras máquinas tejedoras",
    "8153": "Operadores de máquinas de coser",
    "8154": "Operadores de máquinas de blanqueamiento, teñido y limpieza de tejidos",
    "8155": "Operadores de máquinas de tratamiento de pieles y cueros",
    "8156": "Operadores de máquinas para la fabricación de calzado y afines",
    "8157": "Operadores de máquinas de lavandería",
    "8159": "Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero no clasificados en otros grupos primarios",
    "8160": "Operadores de máquinas para elaborar alimentos y productos afines",
    "8171": "Operadores de instalaciones para la preparación de pasta para papel y papel",
    "8172": "Operadores de instalaciones de procesamiento de la madera",
    "8181": "Operadores de máquinas y de instalaciones para elaborar productos de vidrio y cerámica",
    "8182": "Operadores de máquinas de vapor y calderas",
    "8183": "Operadores de máquinas de embalaje, embotellamiento y etiquetado",
    "8189": "Otros operadores de máquinas y de instalaciones fijas no clasificados en otros grupos primarios",
    "8211": "Ensambladores de maquinaria mecánica",
    "8212": "Ensambladores de equipos eléctricos y electrónicos",
    "8219": "Ensambladores no clasificados bajo otros grupos primarios",
    "8311": "Maquinistas de locomotoras",
    "8312": "Guardafrenos, guardagujas y agentes de maniobras",
    "8321": "Conductores de motocicletas",
    "8323": "Conductores de camionetas y vehículos livianos",
    "8324": "Conductores de taxis",
    "8331": "Conductores de buses, microbuses y tranvías",
    "8332": "Conductores de camiones y vehículos pesados",
    "8341": "Operadores de maquinaria agrícola y forestal móvil",
    "8342": "Operadores de máquinas de movimiento de tierras, construcción de vías y afines",
    "8343": "Operadores de grúas, aparatos elevadores y afines",
    "8344": "Operadores de montacargas",
    "8350": "Marineros de cubierta y afines",
    "9111": "Personal doméstico",
    "9112": "Aseadores de oficinas, hoteles y otros establecimientos",
    "9121": "Lavanderos y planchadores manuales",
    "9122": "Lavadores de vehículos",
    "9123": "Lavadores de ventanas",
    "9129": "Otro personal de limpieza no clasificados bajo otros grupos primarios",
    "9211": "Obreros y peones de explotaciones agrícolas",
    "9212": "Obreros y peones de explotaciones ganaderas",
    "9213": "Obreros y peones de explotaciones agropecuarias",
    "9214": "Obreros y peones de jardinería y horticultura",
    "9215": "Obreros y peones forestales",
    "9216": "Obreros y peones de pesca y acuicultura",
    "9311": "Obreros y peones de minas y canteras",
    "9312": "Obreros y peones de obras públicas y mantenimiento",  "9313": "Obreros y peones de la construcción de edificios",
    "9321": "Empacadores manuales",
    "9329": "Obreros y peones de la industria manufacturera no clasificados en otros grupos primarios",
    "9331": "Conductores de vehículos accionados a pedal o a brazo",
    "9332": "Conductores de vehículos y máquinas de tracción animal",
    "9333": "Obreros y peones de carga",
    "9334": "Surtidores de estanterías",
    "9411": "Cocineros de comidas rápidas",
    "9412": "Ayudantes de cocina",
    "9510": "Trabajadores ambulantes de servicios y afines",
    "9520": "Vendedores ambulantes (excluyendo comidas de preparación inmediata)",
    "9611": "Recolectores de basura y material reciclable",
    "9612": "Clasificadores de desechos",
    "9613": "Barrenderos y afines",
    "9621": "Mensajeros, mandaderos, maleteros y repartidores",
    "9622": "Personas que realizan trabajos varios",
    "9624": "Acarreadores de agua y recolectores de leña",
    "9625": "Recolectores de dinero y surtidores de máquinas de venta automática",
    "9626": "Lectores de medidores",
    "9629": "Otras ocupaciones elementales no clasificadas en otros grupos primarios",
    "9998": "Jubilado, desempleado, ama de casa, estudiante, dedicación al hogar, menor de edad",
    "9999": "En los casos en que no se tiene esta información registrar"
}