from aps_api.managers import names
from aps_api.managers import contact
from aps_api.managers import pollster
from aps_api.managers import infoGeneral
from aps_api.managers import family
from aps_api.managers import member
from aps_api.managers import report
from aps_api.managers import livingpPlace
from aps_api.managers import sanitation
from aps_api.managers import familyContext
from aps_api.managers import welfare
from aps_api.managers import pipelines
from aps_api.managers import channelEntity
from aps_api.managers import newFields
